project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!/assets/*.*"
    - "!/notebooks/*.*"
    - "!/forthcoming/*.*"
    - "!.ipynb_checkpoints/"  # exclude ipynb checkpoints
    - "!*/.ipynb_checkpoints/" # exclude in subdirectories
    - "!.DS_Store"
    - "!*/.DS_Store"
  resources:
    - CNAME
    - .nojekyll

site:
  title: "Blog: Gen AI for Finance"
  site-url: https://blog.kerryback.com
  feed:
    type: rss2
  description: "Teaching the use of generative AI in finance"
  navbar:
    title: false
    search: true
    left:
      - icon: house-door-fill
        href: https://genai4finance.kerryback.com
    right:
      - text: Blog
        href: index.qmd
      - text: Syllabus
        href: https://mgmt675-2026.kerryback.com/MGMT675.pdf
        target: _blank
      - text: FMA Tutorial
        href: https://fma2025.kerryback.com
        target: _blank
      - text: FMA Award
        href: "#"
      - text: Python
        href: https://workshop.kerryback.com
        target: _blank

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Kerry Back"

format:
  html:
    code-overflow: wrap
    theme:
      light: flatly
      dark: superhero
      
      
    css: styles.css
    toc: true

execute:
  freeze: auto

comments:
  giscus:
    repo: finance-with-ai/blog
    repo-id: R_kgDOOkPrbQ
    category: General
    category-id: DIC_kwDOOkPrbc4Cpylb
    mapping: pathname
    reactions-enabled: true
    loading: lazy
    input-position: bottom
    theme: preferred_color_scheme 




 